<?php

return [
    'db' => [
        'host' => $_ENV['DB_HOST'] ?? '127.0.0.1',
        'port' => $_ENV['DB_PORT'] ?? '3306',
        'name' => $_ENV['DB_NAME'] ?? 'overseas_warehouse',
        'user' => $_ENV['DB_USER'] ?? 'root',
        'pass' => $_ENV['DB_PASS'] ?? '',
        'charset' => 'utf8mb4',
    ],
    'callback' => [
        'token' => $_ENV['CALLBACK_TOKEN'] ?? 'wh_callback_token_2024',
        'ip_whitelist' => isset($_ENV['CALLBACK_IP_WHITELIST']) ? explode(',', $_ENV['CALLBACK_IP_WHITELIST']) : [
            '127.0.0.1',
            '10.0.0.0/8',
            '192.168.0.0/16',
        ],
    ],
    'order' => [
        'no_prefix' => $_ENV['ORDER_NO_PREFIX'] ?? 'WH',
        'max_quantity_per_item' => (int)($_ENV['ORDER_MAX_QUANTITY_PER_ITEM'] ?? 999),
    ],
    'warehouse' => [
        'default_priority' => (int)($_ENV['WAREHOUSE_DEFAULT_PRIORITY'] ?? 0),
    ],
    'state_machine' => [
        'strict_validation' => $_ENV['STATE_MACHINE_STRICT_VALIDATION'] ?? true,
        'allow_force_transition' => $_ENV['STATE_MACHINE_ALLOW_FORCE_TRANSITION'] ?? false,
        'transition_log_enabled' => $_ENV['STATE_MACHINE_TRANSITION_LOG_ENABLED'] ?? true,
        'rollback_enabled' => $_ENV['STATE_MACHINE_ROLLBACK_ENABLED'] ?? true,
        'max_rollback_depth' => $_ENV['STATE_MACHINE_MAX_ROLLBACK_DEPTH'] ?? 3,
    ],
    'wallet' => [
        'freeze' => [
            'max_single_amount' => (float)($_ENV['WALLET_FREEZE_MAX_SINGLE_AMOUNT'] ?? 100000.00),
            'max_daily_amount' => (float)($_ENV['WALLET_FREEZE_MAX_DAILY_AMOUNT'] ?? 500000.00),
            'max_count_per_dealer' => (int)($_ENV['WALLET_FREEZE_MAX_COUNT_PER_DEALER'] ?? 50),
            'default_expire_hours' => (int)($_ENV['WALLET_FREEZE_DEFAULT_EXPIRE_HOURS'] ?? 72),
            'auto_unfreeze_enabled' => (bool)($_ENV['WALLET_FREEZE_AUTO_UNFREEZE_ENABLED'] ?? true),
            'auto_unfreeze_threshold_hours' => (int)($_ENV['WALLET_FREEZE_AUTO_UNFREEZE_THRESHOLD_HOURS'] ?? 168),
            'allow_partial_unfreeze' => (bool)($_ENV['WALLET_FREEZE_ALLOW_PARTIAL_UNFREEZE'] ?? true),
            'unfreeze_requires_audit' => (bool)($_ENV['WALLET_FREEZE_UNFREEZE_REQUIRES_AUDIT'] ?? false),
            'deduct_requires_audit' => (bool)($_ENV['WALLET_FREEZE_DEDUCT_REQUIRES_AUDIT'] ?? false),
            'no_prefix' => $_ENV['WALLET_FREEZE_NO_PREFIX'] ?? 'FRZ',
        ],
        'balance' => [
            'recharge' => [
                'min_single_amount' => (float)($_ENV['WALLET_RECHARGE_MIN_SINGLE_AMOUNT'] ?? 0.01),
                'max_single_amount' => (float)($_ENV['WALLET_RECHARGE_MAX_SINGLE_AMOUNT'] ?? 500000.00),
                'max_daily_amount' => (float)($_ENV['WALLET_RECHARGE_MAX_DAILY_AMOUNT'] ?? 2000000.00),
                'requires_audit' => (bool)($_ENV['WALLET_RECHARGE_REQUIRES_AUDIT'] ?? false),
                'audit_threshold' => (float)($_ENV['WALLET_RECHARGE_AUDIT_THRESHOLD'] ?? 100000.00),
            ],
            'withdraw' => [
                'min_single_amount' => (float)($_ENV['WALLET_WITHDRAW_MIN_SINGLE_AMOUNT'] ?? 1.00),
                'max_single_amount' => (float)($_ENV['WALLET_WITHDRAW_MAX_SINGLE_AMOUNT'] ?? 200000.00),
                'max_daily_amount' => (float)($_ENV['WALLET_WITHDRAW_MAX_DAILY_AMOUNT'] ?? 500000.00),
                'daily_count_limit' => (int)($_ENV['WALLET_WITHDRAW_DAILY_COUNT_LIMIT'] ?? 10),
                'requires_audit' => (bool)($_ENV['WALLET_WITHDRAW_REQUIRES_AUDIT'] ?? true),
                'audit_threshold' => (float)($_ENV['WALLET_WITHDRAW_AUDIT_THRESHOLD'] ?? 50000.00),
            ],
            'consume' => [
                'min_single_amount' => (float)($_ENV['WALLET_CONSUME_MIN_SINGLE_AMOUNT'] ?? 0.01),
                'max_single_amount' => (float)($_ENV['WALLET_CONSUME_MAX_SINGLE_AMOUNT'] ?? 100000.00),
                'max_daily_amount' => (float)($_ENV['WALLET_CONSUME_MAX_DAILY_AMOUNT'] ?? 1000000.00),
                'allow_negative_balance' => (bool)($_ENV['WALLET_CONSUME_ALLOW_NEGATIVE_BALANCE'] ?? false),
            ],
            'refund' => [
                'max_single_amount' => (float)($_ENV['WALLET_REFUND_MAX_SINGLE_AMOUNT'] ?? 100000.00),
                'requires_audit' => (bool)($_ENV['WALLET_REFUND_REQUIRES_AUDIT'] ?? true),
                'audit_threshold' => (float)($_ENV['WALLET_REFUND_AUDIT_THRESHOLD'] ?? 10000.00),
                'refund_within_days' => (int)($_ENV['WALLET_REFUND_WITHIN_DAYS'] ?? 90),
            ],
        ],
        'reconciliation' => [
            'enabled' => (bool)($_ENV['WALLET_RECONCILIATION_ENABLED'] ?? true),
            'auto_reconcile_hour' => (int)($_ENV['WALLET_RECONCILIATION_AUTO_HOUR'] ?? 3),
            'alert_on_error' => (bool)($_ENV['WALLET_RECONCILIATION_ALERT_ON_ERROR'] ?? true),
            'alert_email' => $_ENV['WALLET_RECONCILIATION_ALERT_EMAIL'] ?? 'admin@example.com',
            'export_encoding' => $_ENV['WALLET_RECONCILIATION_EXPORT_ENCODING'] ?? 'UTF-8',
            'max_export_rows' => (int)($_ENV['WALLET_RECONCILIATION_MAX_EXPORT_ROWS'] ?? 100000),
        ],
        'state_machine' => [
            'strict_validation' => (bool)($_ENV['WALLET_STATE_MACHINE_STRICT_VALIDATION'] ?? true),
            'allow_force_transition' => (bool)($_ENV['WALLET_STATE_MACHINE_ALLOW_FORCE_TRANSITION'] ?? false),
            'transition_log_enabled' => (bool)($_ENV['WALLET_STATE_MACHINE_TRANSITION_LOG_ENABLED'] ?? true),
        ],
    ],
    'security' => [
        'operation_password_required' => $_ENV['OPERATION_PASSWORD_REQUIRED'] ?? true,
        'operation_password_threshold' => (float)($_ENV['OPERATION_PASSWORD_THRESHOLD'] ?? 10000.00),
        'two_factor_required' => $_ENV['TWO_FACTOR_REQUIRED'] ?? false,
        'two_factor_threshold' => (float)($_ENV['TWO_FACTOR_THRESHOLD'] ?? 50000.00),
        'ip_whitelist_enabled' => $_ENV['IP_WHITELIST_ENABLED'] ?? false,
    ],
    'order_audit' => [
        'enabled' => (bool)($_ENV['ORDER_AUDIT_ENABLED'] ?? true),
        'rollback_required' => (bool)($_ENV['ORDER_AUDIT_ROLLBACK_REQUIRED'] ?? true),
        'rollback_threshold' => (float)($_ENV['ORDER_AUDIT_ROLLBACK_THRESHOLD'] ?? 10000.00),
        'exception_mark_required' => (bool)($_ENV['ORDER_AUDIT_EXCEPTION_MARK_REQUIRED'] ?? false),
        'exception_mark_threshold' => (float)($_ENV['ORDER_AUDIT_EXCEPTION_MARK_THRESHOLD'] ?? 0),
        'status_change_required' => (bool)($_ENV['ORDER_AUDIT_STATUS_CHANGE_REQUIRED'] ?? false),
        'status_change_threshold' => (float)($_ENV['ORDER_AUDIT_STATUS_CHANGE_THRESHOLD'] ?? 0),
        'writeback_required' => (bool)($_ENV['ORDER_AUDIT_WRITEBACK_REQUIRED'] ?? false),
        'writeback_threshold' => (float)($_ENV['ORDER_AUDIT_WRITEBACK_THRESHOLD'] ?? 0),
        'exception_resolve_required' => (bool)($_ENV['ORDER_AUDIT_EXCEPTION_RESOLVE_REQUIRED'] ?? true),
        'exception_resolve_threshold' => (float)($_ENV['ORDER_AUDIT_EXCEPTION_RESOLVE_THRESHOLD'] ?? 0),
    ],
    'order_rollback_protection' => [
        'enabled' => (bool)($_ENV['ORDER_ROLLBACK_PROTECTION_ENABLED'] ?? true),
        'default_amount_threshold' => (float)($_ENV['ORDER_ROLLBACK_PROTECTION_AMOUNT_THRESHOLD'] ?? 50000.00),
        'time_window_hours' => (int)($_ENV['ORDER_ROLLBACK_PROTECTION_TIME_WINDOW_HOURS'] ?? 24),
        'terminal_status_protected' => (bool)($_ENV['ORDER_ROLLBACK_PROTECTION_TERMINAL_STATUS'] ?? true),
        'max_rollback_count' => (int)($_ENV['ORDER_ROLLBACK_PROTECTION_MAX_ROLLBACK_COUNT'] ?? 3),
    ],
    'order_exception' => [
        'enabled' => (bool)($_ENV['ORDER_EXCEPTION_ENABLED'] ?? true),
        'auto_detect_enabled' => (bool)($_ENV['ORDER_EXCEPTION_AUTO_DETECT_ENABLED'] ?? true),
        'notify_enabled' => (bool)($_ENV['ORDER_EXCEPTION_NOTIFY_ENABLED'] ?? true),
        'notify_email' => $_ENV['ORDER_EXCEPTION_NOTIFY_EMAIL'] ?? 'admin@example.com',
        'high_level_auto_escalate' => (bool)($_ENV['ORDER_EXCEPTION_HIGH_LEVEL_AUTO_ESCALATE'] ?? true),
        'escalate_hours' => (int)($_ENV['ORDER_EXCEPTION_ESCALATE_HOURS'] ?? 24),
    ],
    'order_writeback' => [
        'enabled' => (bool)($_ENV['ORDER_WRITEBACK_ENABLED'] ?? true),
        'max_retry_count' => (int)($_ENV['ORDER_WRITEBACK_MAX_RETRY_COUNT'] ?? 3),
        'retry_interval_seconds' => (int)($_ENV['ORDER_WRITEBACK_RETRY_INTERVAL'] ?? 60),
        'target_systems' => [
            'erp' => (bool)($_ENV['ORDER_WRITEBACK_ERP_ENABLED'] ?? true),
            'wms' => (bool)($_ENV['ORDER_WRITEBACK_WMS_ENABLED'] ?? true),
            'crm' => (bool)($_ENV['ORDER_WRITEBACK_CRM_ENABLED'] ?? false),
            'finance' => (bool)($_ENV['ORDER_WRITEBACK_FINANCE_ENABLED'] ?? true),
        ],
    ],
];
